In [3]:
import numpy as np

## Numpy Array

In [4]:
liste = [20,30,40]

In [5]:
type(liste)

list

In [6]:
liste = np.array(liste)

In [7]:
type(liste)

numpy.ndarray

In [8]:
matrixListe = [[10,20,30],[15,25,35],[1,2,3]]

In [9]:
matrixListe

[[10, 20, 30], [15, 25, 35], [1, 2, 3]]

In [10]:
matrixListe[0]

[10, 20, 30]

In [11]:
np.array(matrixListe)

array([[10, 20, 30],
       [15, 25, 35],
       [ 1,  2,  3]])

In [15]:
numpy_array=np.array([0,1,2,3,4,5])
print(numpy_array.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [17]:
dizi=np.array(['A','B','C','D'])
print(dizi)
print(dizi)

['A' 'B' 'C' 'D']
['A' 'B' 'C' 'D']
