In [1]:
import numpy as np

In [4]:
benimDizim = np.arange(0,15)

In [5]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [11]:
benimDizim[3:8] = -5

In [12]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
baskaDizi = np.arange(0,24)

In [15]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
slicingDizi = baskaDizi[4:9]

In [33]:
slicingDizi

array([700, 700, 700, 700, 700])

In [34]:
slicingDizi[:] = 700

In [35]:
slicingDizi

array([700, 700, 700, 700, 700])

In [36]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## Ana dizi değişmesin istiyorsak copy() kullanırız.

In [37]:
ornekDizi = np.arange(0,24)

In [38]:
ornekDiziKopyasi = ornekDizi.copy()

In [39]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[4:9]

In [40]:
ornekDiziKopyasiSlicing

array([4, 5, 6, 7, 8])

In [41]:
ornekDiziKopyasiSlicing[:] = 300

In [42]:
ornekDiziKopyasiSlicing

array([300, 300, 300, 300, 300])

In [43]:
ornekDiziKopyasi

array([  0,   1,   2,   3, 300, 300, 300, 300, 300,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [45]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix Indexler

In [47]:
benimListem = [[10,20,30],[20,30,40],[15,25,35]]

In [48]:
benimMatrixDizim = np.array(benimListem)

In [49]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [15, 25, 35]])

In [56]:
benimMatrixDizim[0][1]

20

In [57]:
benimMatrixDizim[0,1]

20

In [61]:
benimMatrixDizim[0:,2]

array([30, 40, 35])

In [62]:
benimMatrixDizim[0:,0:]

array([[10, 20, 30],
       [20, 30, 40],
       [15, 25, 35]])

In [64]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [66]:
yeniMatrix =  np.array(yeniListe)

In [70]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

## Numpy Operasyonlar

In [84]:
yeniBirDizi = np.random.randint(1,100,20)

In [85]:
yeniBirDizi

array([ 9, 78, 83, 97, 96, 93, 51, 72, 98, 48, 20, 94, 27, 13, 56, 84, 32,
       33,  2, 43])

In [89]:
sonucDizi = yeniBirDizi > 50

In [95]:
sonucDizi

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True, False, False,
       False, False])

In [94]:
yeniBirDizi[yeniBirDizi > 50]

array([78, 83, 97, 96, 93, 51, 72, 98, 94, 56, 84])

In [96]:
sonDizi = np.arange(0,24)

In [97]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [98]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [100]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [101]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [102]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [103]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [104]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [105]:
sonDizi / sonDizi # 0/0 sonucu nandır(Not a Number) ve hata vermesi gerekir.  ancak  buna rağmen çalışmaya devam ediyor.

C:\Users\Doğukan\AppData\Local\Temp\ipykernel_12772\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [106]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [107]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [108]:
np.max(sonDizi)

23

In [109]:
np.min(sonDizi)

0

In [113]:
np.argmax(sonDizi)

23

In [114]:
np.argmin(sonDizi)

0